language: csharp
solution: Rick.sln
git:
  depth: 1
branches:
  only:
  - master
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    mono: none
    dotnet: 2.0.0-preview1-002111-00
    env: DOTNETCORE=2
script:
  - sudo apt-get install dotnet-dev-1.0.0-rc4-004771
  - dotnet restore --configfile nuget.config
  - dotnet build
