version: 18.4.{build}
skip_tags: true
image: Visual Studio 2017
clone_folder: C:\Projects\Valerie
build:
  verbosity: detailed
before_build:
- cmd: >-
    dotnet restore
build_script:
- cmd: >-
    dotnet build
artifacts:
- path: bin\Debug\netcoreapp2.0\Valerie.dll
  name: ValerieRewrite
deploy:
- provider: GitHub
  release: Betav$(appveyor_build_version)
  description: On going beta rewrite. Will be finished soon. Currently rewriting modules.
  auth_token:
    secure: nEHV/UOH6M27jySdtWUJM4D3kbi1B3JL14t5w9FbYTgNwMV4ZtZl5uAJ5VzlNmHk
  artifact: ValerieRewrite
  prerelease: true
