version: 18.4.{build}
image: Visual Studio 2017
clone_folder: C:\Projects\Valerie
build:
  verbosity: detailed
before_build:
- cmd: >-
    dotnet restore
build_script:
- cmd: >-
    dotnet build
artifacts:
- path: C:\Projects\Valerie\bin\Debug\netcoreapp2.0\Valerie.dll
  name: Valerie-beta
deploy:
- provider: GitHub
  release: Beta
  description: Beta rewrite
  auth_token:
    secure: nEHV/UOH6M27jySdtWUJM4D3kbi1B3JL14t5w9FbYTgNwMV4ZtZl5uAJ5VzlNmHk
  artifact: .dll
  prerelease: true
