version: 18.4.{build}
image: Visual Studio 2017
clone_folder: C:\Projects\Valerie
build:
  verbosity: detailed  
before_build:
- cmd: >-
    dotnet restore
build_script:
- cmd: >-
    dotnet build
deploy:
- provider: GitHub
  release: Beta
  description: Beta rewrite
  auth_token:
    secure: Ec8aEBaQI0OfIUNnutSWCSgn97CV21IWwhZYIyNDvMaWesVrEP6KO43IeV0KUuofiEN0s0jl6dKj+R11Fhvggw==
  repository: Yucked/Valerie
  artifact: .dll
  prerelease: true
