version: 18.4.{build}
skip_tags: true
image: Visual Studio 2017 Preview
shallow_clone: true
clone_folder: C:\Projects\Valerie
skip_commits:
  message: /Update/
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet build
artifacts:
- path: bin\Debug\netcoreapp2.1
  name: Stable-$(appveyor_build_version)-Core2.1
- path: bin\Debug\netcoreapp2.0
  name: Stable-$(appveyor_build_version)-Core2.0
deploy:
- provider: GitHub
  tag: Stable
  release: Stable
  description: Stable Release! Little bug fixes here and there.
  auth_token:
    secure: nEHV/UOH6M27jySdtWUJM4D3kbi1B3JL14t5w9FbYTgNwMV4ZtZl5uAJ5VzlNmHk
  artifact: Stable-$(appveyor_build_version)-Core2.1, Stable-$(appveyor_build_version)-Core2.0
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
