version: 18.4.{build}
skip_tags: true
image: Visual Studio 2017
skip_commits:
  message: /Update/
  author: Yucked
clone_folder: C:\Projects\Valerie
shallow_clone: true
clone_depth: 2
configuration: Debug
build:
  parallel: true
  verbosity: detailed  
before_build:
- cmd: >-
    dotnet restore
build_script:
- cmd: >-
    dotnet build
artifacts:
- path: bin\Debug\netcoreapp2.0
  name: ValerieRewrite
deploy:
- provider: GitHub
  release: Beta-v$(appveyor_build_version)
  description: On going beta rewrite. Will be finished soon. Currently rewriting modules.
  auth_token:
    secure: nEHV/UOH6M27jySdtWUJM4D3kbi1B3JL14t5w9FbYTgNwMV4ZtZl5uAJ5VzlNmHk
  artifact: ValerieRewrite
  prerelease: true
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/433746401298481154/5N2Lz_sX1WgSDh74HwEtNjXllaRfrPl4tQ1dxxRuWJnvUwyPtgJKJwLZ8kxGCcxNLhEZ
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true  
