namespace Valerie.Handlers.GuildHandler.Enum
{
    public enum ModelEnum
    {
        Prefix,
        MuteId,
        ModCases,
        AntiAdvertisement,
        KarmaEnabled,
        WelcomeAdd,
        WelcomeRemove,
        LeaveAdd,
        LeaveRemove,
        RolesAdd,
        RolesRemove,
        JoinChannel,
        JoinEnabled,
        LeaveChannel,
        LeaveEnabled,
        ModChannel,
        ModEnabled,
        CBChannel,
        CBEnabled,
        StarChannel,
        StarEnabled,
        TagAdd,
        TagRemove,
        TagModify,
        TagUpdate,
        AFKAdd,
        AFKRemove,
        AFKModify,
        KarmaAdd,
        KarmaDelete,
        KarmaUpdate,
        KarmaSubtract
    }
}
